---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: Install packages
  apt: 
    name: "{{ item }}"
    state: present
  loop: 
    - software-properties-common
    - awscli
    - unzip
- name: Add python3 repository to ubuntu
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
- name: Install Python3.8
  apt: 
    name: "{{ item }}"
    state: present
  loop: 
    - python3.8
    - python3-pip
    - python-pip
- name: Install virtualenv module
  pip:
    name: virtualenv
- name: Create Python3-virtual environment folder
  file:
    name: /home/ubuntu/venv
    state: directory
- name: copying file with playbook
  become: true 
  copy:
    src: requirements.txt
    dest: /home/ubuntu/venv/requirements.txt
- name: Create Python3-virtual requirements.txt
  command: touch /home/ubuntu/venv/requirements.txt
  args:
    creates: /home/ubuntu/venv/requirements.txt
- name: Install python reqs globally
  pip: 
    requirements: /home/ubuntu/venv/requirements.txt
- name: create virtual env
  pip: 
    virtualenv: /home/ubuntu/venv
    virtualenv_python: python3.8
    requirements: /home/ubuntu/venv/requirements.txt